FROM node:20-alpine
RUN apk add --no-cache openssl
WORKDIR /app
COPY scoring/backend/package*.json ./
RUN npm install
COPY database/prisma ./prisma
RUN npx prisma generate
COPY scoring/backend/. .
EXPOSE 4000
CMD ["npm", "run", "dev"]
